<a href="https://colab.research.google.com/github/n-jagadeep/ICP3/blob/main/ICP3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

PROBLEM 1

In [25]:
class Employee:
    numberOfEmployees = 0

    def __init__(self, name, family, salary, department):
        self.name = name
        self.family = family
        self.salary = salary
        self.department = department
        Employee.numberOfEmployees+=1


def averagesalary(employee):
    total = sum(e.salary for e in employee)
    average = total / len(employee)
    return average

class FulltimeEmployee(Employee):
    def __init__(self, name, family, salary, department):
        Employee.__init__(self,name, family, salary, department)

print("Employee 1: ")
employee1 = Employee(input("Enter name: "),input("Family Members: "),int(input("Employee Salary: ")),input("Employee Department: "))
print("Employee 2: ")
employee2 = Employee(input("Enter name: "),input("Family Members: "),int(input("Employee Salary: ")),input("Employee Department: "))
print("Full Time Employee 1: ")
employee3 = FulltimeEmployee(input("Enter name: "),input("Family Members: "),int(input("Employee Salary: ")),input("Employee Department: "))
print("")
print("Number of employees: ",Employee.numberOfEmployees)
listofEmployees = [employee1, employee2]
avgsalary = averagesalary(listofEmployees)
print("Avg salary is :", avgsalary)



Employee 1: 
Enter name: dsfh
Family Members: fshd
Employee Salary: 4325
Employee Department: sfhd
Employee 2: 
Enter name: sfhd
Family Members: wger
Employee Salary: 3451
Employee Department: gsf
Full Time Employee 1: 
Enter name: hfds
Family Members: gwfe
Employee Salary: 3425
Employee Department: shg

Number of employees:  3
Avg salary is : 3888.0


PROBLEM 2

In [30]:
import numpy

random_vector = numpy.random.uniform(1, 20, 20)
print(random_vector)
print("")
print("")
reshaped_array = random_vector.reshape(4, 5)
print("")
print("")
print(reshaped_array)
reshaped_array[numpy.arange(4), numpy.argmax(reshaped_array, axis=1)] = 0
print("")
print("")
print(reshaped_array)


[19.36250254  4.02065227  7.57538185  5.2104046   2.37936772 15.92259052
 16.37455234  6.42552621  9.62903538  8.30567078 12.91243973 14.05974304
 12.18184864 19.53936696  8.62504968  2.03570144 15.97263122 14.27802934
  7.90991108  3.99176931]




[[19.36250254  4.02065227  7.57538185  5.2104046   2.37936772]
 [15.92259052 16.37455234  6.42552621  9.62903538  8.30567078]
 [12.91243973 14.05974304 12.18184864 19.53936696  8.62504968]
 [ 2.03570144 15.97263122 14.27802934  7.90991108  3.99176931]]


[[ 0.          4.02065227  7.57538185  5.2104046   2.37936772]
 [15.92259052  0.          6.42552621  9.62903538  8.30567078]
 [12.91243973 14.05974304 12.18184864  0.          8.62504968]
 [ 2.03570144  0.         14.27802934  7.90991108  3.99176931]]
